import type { Engine } from './connection';

/** Palabras clave y funciones para el autocompletado (specs/05), comunes y por dialecto. */

const COMMON_KEYWORDS = [
  'SELECT',
  'FROM',
  'WHERE',
  'AND',
  'OR',
  'NOT',
  'IN',
  'IS',
  'NULL',
  'LIKE',
  'BETWEEN',
  'EXISTS',
  'AS',
  'DISTINCT',
  'ALL',
  'ANY',
  'JOIN',
  'INNER',
  'LEFT',
  'RIGHT',
  'FULL',
  'OUTER',
  'CROSS',
  'ON',
  'USING',
  'GROUP BY',
  'ORDER BY',
  'HAVING',
  'ASC',
  'DESC',
  'UNION',
  'UNION ALL',
  'EXCEPT',
  'INTERSECT',
  'CASE',
  'WHEN',
  'THEN',
  'ELSE',
  'END',
  'INSERT INTO',
  'VALUES',
  'UPDATE',
  'SET',
  'DELETE FROM',
  'WITH',
  'CREATE',
  'TABLE',
  'VIEW',
  'INDEX',
  'ALTER',
  'DROP',
  'ADD',
  'COLUMN',
  'PRIMARY KEY',
  'FOREIGN KEY',
  'REFERENCES',
  'UNIQUE',
  'CHECK',
  'DEFAULT',
  'CONSTRAINT',
  'TRUNCATE',
  'BEGIN',
  'COMMIT',
  'ROLLBACK',
  'GRANT',
  'REVOKE',
  'TRUE',
  'FALSE',
  'OVER',
  'PARTITION BY',
];

const DIALECT_KEYWORDS: Record<Engine, string[]> = {
  postgres: [
    'LIMIT',
    'OFFSET',
    'RETURNING',
    'ILIKE',
    'ON CONFLICT',
    'DO NOTHING',
    'LATERAL',
    'FILTER',
    'SCHEMA',
    'SEQUENCE',
    'MATERIALIZED VIEW',
    'EXPLAIN',
    'ANALYZE',
  ],
  mariadb: [
    'LIMIT',
    'OFFSET',
    'REPLACE',
    'IGNORE',
    'ON DUPLICATE KEY UPDATE',
    'SHOW',
    'DESCRIBE',
    'USE',
    'DATABASE',
    'ENGINE',
    'AUTO_INCREMENT',
    'EXPLAIN',
  ],
  sqlite: [
    'LIMIT',
    'OFFSET',
    'RETURNING',
    'PRAGMA',
    'ATTACH',
    'DETACH',
    'VACUUM',
    'WITHOUT ROWID',
    'AUTOINCREMENT',
    'EXPLAIN QUERY PLAN',
  ],
  sqlserver: [
    'TOP',
    'OFFSET',
    'FETCH NEXT',
    'ROWS ONLY',
    'OUTPUT',
    'MERGE',
    'NOLOCK',
    'GO',
    'DECLARE',
    'PRINT',
    'EXEC',
    'BEGIN TRAN',
    'IDENTITY',
    'APPLY',
  ],
};

const COMMON_FUNCTIONS = [
  'COUNT',
  'SUM',
  'AVG',
  'MIN',
  'MAX',
  'COALESCE',
  'NULLIF',
  'CAST',
  'UPPER',
  'LOWER',
  'TRIM',
  'LTRIM',
  'RTRIM',
  'REPLACE',
  'SUBSTRING',
  'ABS',
  'ROUND',
  'FLOOR',
  'CEILING',
  'ROW_NUMBER',
  'RANK',
  'DENSE_RANK',
  'LAG',
  'LEAD',
];

const DIALECT_FUNCTIONS: Record<Engine, string[]> = {
  postgres: [
    'NOW',
    'CURRENT_DATE',
    'CURRENT_TIMESTAMP',
    'DATE_TRUNC',
    'EXTRACT',
    'TO_CHAR',
    'TO_DATE',
    'STRING_AGG',
    'ARRAY_AGG',
    'JSONB_BUILD_OBJECT',
    'JSON_AGG',
    'GENERATE_SERIES',
    'LENGTH',
    'CONCAT',
    'SPLIT_PART',
    'AGE',
  ],
  mariadb: [
    'NOW',
    'CURDATE',
    'CURRENT_TIMESTAMP',
    'DATE_FORMAT',
    'DATE_ADD',
    'DATE_SUB',
    'DATEDIFF',
    'IFNULL',
    'IF',
    'GROUP_CONCAT',
    'CONCAT',
    'CONCAT_WS',
    'LENGTH',
    'JSON_OBJECT',
    'JSON_EXTRACT',
    'LAST_INSERT_ID',
  ],
  sqlite: [
    'DATE',
    'TIME',
    'DATETIME',
    'JULIANDAY',
    'STRFTIME',
    'IFNULL',
    'IIF',
    'GROUP_CONCAT',
    'LENGTH',
    'INSTR',
    'PRINTF',
    'JSON_OBJECT',
    'JSON_EXTRACT',
    'TYPEOF',
    'LAST_INSERT_ROWID',
  ],
  sqlserver: [
    'GETDATE',
    'SYSDATETIME',
    'DATEADD',
    'DATEDIFF',
    'DATEPART',
    'FORMAT',
    'CONVERT',
    'ISNULL',
    'IIF',
    'STRING_AGG',
    'LEN',
    'CONCAT',
    'CHARINDEX',
    'NEWID',
    'SCOPE_IDENTITY',
    'TRY_CAST',
    'TRY_CONVERT',
  ],
};

export function keywordsFor(engine: Engine | undefined): string[] {
  return [...COMMON_KEYWORDS, ...(engine ? DIALECT_KEYWORDS[engine] : ['LIMIT'])];
}

export function functionsFor(engine: Engine | undefined): string[] {
  return [...new Set([...COMMON_FUNCTIONS, ...(engine ? DIALECT_FUNCTIONS[engine] : [])])];
}

/** Snippets de specs/05 (`$1`, `$0`: posiciones del cursor de Monaco). */
export const SQL_SNIPPETS: { label: string; detail: string; body: string }[] = [
  { label: 'sel', detail: 'SELECT * FROM …', body: 'SELECT * FROM ${1:tabla} ${0}' },
  {
    label: 'ins',
    detail: 'INSERT INTO … VALUES …',
    body: 'INSERT INTO ${1:tabla} (${2:columnas})\nVALUES (${3:valores});${0}',
  },
  {
    label: 'upd',
    detail: 'UPDATE … SET … WHERE …',
    body: 'UPDATE ${1:tabla}\nSET ${2:columna} = ${3:valor}\nWHERE ${4:condición};${0}',
  },
  {
    label: 'del',
    detail: 'DELETE FROM … WHERE …',
    body: 'DELETE FROM ${1:tabla}\nWHERE ${2:condición};${0}',
  },
  {
    label: 'cte',
    detail: 'WITH … AS (…) SELECT …',
    body: 'WITH ${1:nombre} AS (\n\t${2:SELECT 1}\n)\nSELECT * FROM ${1:nombre};${0}',
  },
];
